export default {
    python: "Python",
    sqlite: "SQLite",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    node: "Node.js",
    vscode: "VSCode",
    nvim: "NeoVim",
    figma: "Figma",
    git: "Git & GitHub",
    react: "React",
    flask: "Flask",
    js: "JavaScript",
    python: "Python",
    c: "C",
    cpp: "C++",
    csharp: "C#",
    swift: "Swift",
    objc: "Objective-C",
    shell: "Shell Scripting",
    sqlite: "SQLite",
    mysql: "MySQL",
    mongo: "MongoDB",
    postgreSql: "PostgreSQL",
    html: "HTML",
    css: "CSS",
    flask: "Flask",
    django: "Django",
    swiftui: "SwiftUI",
    uikit: "UIKit",
    opencv: "OpenCV",
    pillow: "Pillow",
    scikitImage: "scikit-image",
    pandas: "Pandas",
    numpy: "NumPy",
    matplotlib: "Matplotlib",
    restapi: "RESTful APIs",
    json: "JSON",
    vscode: "VSCode",
    xcode: "Xcode",
    pycharm: "PyCharm",
    postman: "Postman",
    git: "Git & GitHub",
    gitlab: "GitLab",
    jenkins: "Jenkins",
    jira: "Jira",
    ci: "CI/CD",
    linux: "Linux",
    embeddedlinux: "Embedded Linux",
    windows: "Windows",
    macos: "macOS",
    react: "React",
    flutter: "Flutter",
    bus: "CAN / LIN / Automotive Ethernet",
    hiloops: "HiL Systems (dSPACE)",
    testing: "Testautomatisierung",
    unitTest: "Unit Testing",
    agile: "Agile Development / Scrum",
    apiIntegration: "API Integration",
    softwarearch: "Software Architecture",
    multithreading: "Multithreading & Async Programming",
    modeling: "Systemmodellierung",
    docs: "Technische Dokumentation",
    docker: "Docker",
    coredata: "CoreData",
    ios: "iOS",
    URLRequest: "URLSession",
    URLSession: "URLSession",
    WebKit: "WebKit",
    cnn: "Convolutional Neural Networks",
    ml: "Machine Learning",
    jupyter: "Jupyter Notebook",
    svm: "Support Vector Machines",
    sklearn: "scikit-learn",
    imageclassification: "Image Classification",
    api: "RESTful APIs",
    gitgithub: "Git & GitHub",
    manual: "Manual Tests",

}